name: Print all environment variables
on:
  pull_request_target:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: icr.io/goldeneye_images/goldeneye-ci-image:stable
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Print all environment variables
        run: env
      - name: Git commands
        run: |
            git config --global --add safe.directory $(pwd)
            echo "--------------"
            echo "the root directory of the current Git repository:"
            git rev-parse --show-toplevel
            echo "--------------"
            echo "all symbolic references:"
            git for-each-ref --format="%(refname)" refs/
            echo "--------------"
            echo "symbolic reference for the default branch:"
            git remote show origin | grep "HEAD branch" | awk '{print $NF}'
            echo "--------------"
            echo "retrieves the URL of the remote repository:"
            git remote get-url origin
            echo "--------------"
        if: success() # Ensure this step runs only if the checkout was successful

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20' # Use the Go version you need

      - name: TestGo
        run: |
          go test $(go list ./... | grep -v /common-dev-assets/) -count=1 -v -timeout 5m

      - name: Build Go program
        run: go build -o sample ./main.go
        working-directory: ${{ github.workspace }}

      - name: Run Go program
        run: ./sample
        working-directory: ${{ github.workspace }}
