name: Print all environment variables
on:
  push:
  pull_request_target:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - name: Print all environment variables
        run: env
      - name: Git commands
        run: |
            echo "--------------"
            echo "the root directory of the current Git repository:"
            git rev-parse --show-toplevel
            echo "--------------"
            echo "symbolic reference for the default branch:"
            git symbolic-ref refs/remotes/origin/HEAD
            echo "--------------"
            echo "retrieves the URL of the remote repository:"
            git remote get-url origin
            echo "--------------"
